---
- hosts: all
  user: user
  become: yes
  gather_facts: no
  tasks:
    - name: Run uptime
      raw: /usr/bin/uptime >> /home/user/uptime.log
    - name: List var
      raw: ls -la /var >> /home/user/dir.list
      run_once: true
