version: '3'
services:
   nginx:
     image: nginx 
     ports:
       - "80:80"
     links:
       - php
       - mysql
     volumes:
       - /docker/nginx/www:/var/www/
       - /docker/nginx/logs:/var/logs/nginx
   php:
     image: php
     ports:
       - "9000:9000"
       - /docker/nginx/www:/var/www/
   mysql:
     image: mariadb
     ports:
       - "3306:3306"
     volumes:
       - /docker/mysql/database:/var/lib/mysql
