--- #
- hosts: localhost
  connection: ssh  
  user: ansible
  become: yes
  tasks:
    - include_vars: ../mysql/vars/database.yml
    - name: Copy config file
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
    - name: Change config of wordpress
      lineinfile: dest=/var/www/wordpress/wp-config.php
                  regexp={{ item.regexp }}
                  line={{ item.line }}
      with_items:
        - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{ mysql.database }}');"}
        - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{ mysql.user }}');"}
        - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{ mysql.password}}');"}
