version: "3"
services:
  nginx:
    image: nginx:latest 
    ports:
      - "80:80"
    links:
      - php
      - mysql
    volumes:
      - ./nginx/www:/var/www
      - ./nginx/logs:/var/logs/nginx
  php:
    image: php:latest
    ports:
      - "9000:9000"
    volumes:
      - ./nginx/www:/var/www
  mysql:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/database:/var/lib/mysql
